healthblog/healthblog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', 'blog.views.index', name='home'),
	url(r'^articles/$', 'blog.views.index', name='articles'),
	url(r'^tags/([\w-]+)/$', 'blog.views.tag'),
	url(r'^add_article/$', 'blog.views.add_article', name='add_article'),
	url(r'^login/$', 'django.contrib.auth.views.login'),
	url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': "/"}),
	url(r'^register/$', 'blog.views.register', name='register'),
	url(r'^goto/$', 'blog.views.track_url', name='track_url'),
	url(r'^about/$', 'blog.views.about', name='about'),

    url(r'^admin/', include(admin.site.urls)),
)

healthblog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.
class Publisher(models.Model):
	name = models.CharField(max_length=128, unique=True)
	image = models.URLField(default="")
	url = models.URLField()

	def __unicode__(self):
		return self.name

class Article(models.Model):
	title = models.CharField(max_length=200)
	url = models.URLField()
	blurb = models.TextField(max_length=500)
	image = models.URLField(default="")
	views = models.IntegerField(default=0)
	author = models.ForeignKey(User)
	timestamp = models.DateTimeField(auto_now_add=True)
	date_published = models.DateField(default=datetime.date.today)
	publisher = models.ForeignKey(Publisher)

	def __unicode__(self):
		return self.title

class Tag(models.Model):
	articles = models.ManyToManyField(Article)
	name = models.CharField(max_length=128, unique=True)
	topic_tag = models.BooleanField(default=False)
	article_count = models.IntegerField(default=0)

	def __unicode__(self):
		return self.name

healthblog/blog/forms.py
from django import forms
from blog.models import Article, Publisher
from django.contrib.auth.models import User

class ArticleForm(forms.ModelForm):
	class Meta:
		model = Article
		fields = ('author', 'title','url',  'tags', 'blurb', 'image', 'date_published', 'publisher' )
		widgets = {
                'author': forms.HiddenInput()
            }
	tags = forms.CharField(max_length=100, required=False)

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ('username', 'email', 'password')

healthblog/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Article, Tag
from blog.forms import ArticleForm, UserForm
import urllib
from datetime import datetime
from django.contrib.auth.decorators import login_required

# home page / index page with the 20 most recent articles
def index(request):
	articles = Article.objects.all().order_by('-timestamp')[:20]
	topic_tags, other_tags = get_tag_lists()
	context = {
		'articles': articles,
		'topic_tags': topic_tags,
		'other_tags': other_tags,
	}

	if request.session.get('last_visit'):
		last_visit_time = request.session.get('last_visit')
		visits = request.session.get('visits',0)

		if (datetime.now() - datetime.strptime(last_visit_time[:-7], "%Y-%m-%d %H:%M:%S")).days > 0:
			request.session['visits'] = visits + 1
			request.session['last_visit'] = str(datetime.now())
	else:
		request.session['last_visit'] = str(datetime.now())
		request.session['visits'] = 1 		

	return render(request, 'index.html', context)

# tag page with relevant tagged articles
def tag(request, tag_name):
	tag_clean = tag_name.replace("_"," ")
	tag = get_object_or_404(Tag, name=tag_name)
	articles = tag.articles.all()
	topic_tags, other_tags = get_tag_lists()

	context = {
		'tag' : tag,
		'articles': articles,
		'title': tag_clean,
		'topic_tags': topic_tags,
		'other_tags': other_tags,
	}
	return render(request, 'tag.html', context)

# list of tags for the sidebar
def get_tag_lists():
	topic_tags = Tag.objects.filter(topic_tag=True).order_by('-article_count')
	for tag in topic_tags:
		tag.clean_name = tag.name.replace('_', ' ')
	other_tags = Tag.objects.filter(topic_tag=False).order_by('-article_count')
	for tag in other_tags:
		tag.clean_name = tag.name.replace('_', ' ')

	return topic_tags, other_tags

# add article page with form to add an article
@login_required
def add_article(request):
	# context = RequestContext(request)
	topic_tags, other_tags = get_tag_lists()
	current_user = request.user

	if request.method == 'POST':
		form = ArticleForm(request.POST)
		if form.is_valid():
			new_article = form.save()
			raw_tags = form.cleaned_data['tags'].split(',')
			if raw_tags:
				for raw_tag in raw_tags:
					raw_tag = raw_tag.strip().replace(' ', '_').lower()
					tag_name = urllib.quote(raw_tag)
					tag, created = Tag.objects.get_or_create(name=tag_name)
					if created:
						tag.article_count=1
					else:
						tag.article_count +=1
					tag.save()
					tag.articles.add(new_article)
			return redirect(index)
		else:
			print form.errors
	else:
		form = ArticleForm(initial={'author': current_user})

	context = {
		'form': form,
		'topic_tags': topic_tags,
		'other_tags': other_tags,
	}

	return render(request, 'add_article.html', context)	

def register(request):
	# context = RequestContext(request)
	registered = False
	if request.method == 'POST':
		user_form = UserForm(data=request.POST)

		if user_form.is_valid():
			user = user_form.save()
			user.set_password(user)
			user.save()
			registered = True

		else:
			print user_form.errors

	else:
		user_form = UserForm()

	context = {
		'user_form': user_form,
		'registered': registered
	}

	return render(request, 'registration/register.html', context)		

def track_url(request):
	article_id = None
	if request.method == 'GET':
		if 'article_id' in request.GET:
			article_id = request.GET['article_id']
			
			try:
				article = Article.objects.get(id=article_id)
				article.views = article.views +1
				article.save()
				url = article.url
			except:
				pass
			return redirect(url)
	return redirect(index)

def about(request):
	return render(request,'about.html')

healthblog/blog/templates/about.html
{% extends 'base.html' %}

{% block subheader %}About{% endblock %}

{% block sidebar %}
{% endblock %}

{% block content %}
	This website was created by <a href="https://www.linkedin.com/pub/karenne-eng/2/716/944">Karenne Eng</a>, enthusiast programmer and digital health nut.
	<br>

	It was written in <a href="https://www.python.org/">Python</a> using the <a href="https://www.djangoproject.com/">Django</a> framework and utilizes <a href="http://getbootstrap.com/">Bootstrap</a> for styling. 

	 <br>

	 Find me on Twitter <a href="https://twitter.com/karenneeng">here</a>.


{% endblock %}

healthblog/blog/templates/add_article.html
{% extends 'base.html' %}

{% block subheader %} Add an Article {% endblock %}


{% block content %}
<div id="new-bookmark-widget">
	<form method="post">
		{% csrf_token %}
		<h3>Article</h3>
		{{ form.as_p }}
		<p><button id="new-article-submit">Submit</button>
	</form>
</div>

{% endblock %}

healthblog/blog/templates/base.html
<!doctype html>
{% load static %}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap-fluid-adj.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">

	<title>{% block title %}Digital Health Digest{% endblock %}</title>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51803340-1', 'digihealthdigest.com');
  ga('send', 'pageview');

</script>

</head>

<body>
	
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="brand" href="/articles/">Digital Health Digest</a>

				<div class="nav-collapse collapse">
					<ul class="nav pull-right">
						{% if user.is_authenticated %}
						<li class="navbar-text">Welcome, {{ user.username }}!</li>
						<li><a href="/logout/">Logout</a></li>
						{% else %}
						<!-- <li><a href="/register/">Register</a></li> -->
						<li><a href="/login/">Login</a></li>
						{% endif %}
					</ul>
					<ul class="nav">
						{% if user.is_authenticated %}
						<li><a href="/add_article/">Add Article</a></li>
						{% endif %}
						<li><a href="/about/">About</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>


	<div class="container-fluid">
		<div class ="row-fluid">
			<div class="span3">
				<div class="well sidebar-nav">
				{% block sidebar %}
					<div id="tags">
						{% include 'tag_list.html' %}
					</div>
				{% endblock %}
					
				</div> 
			</div>
			<div class="span9">
				<h2>{% block subheader %}{% endblock %}</h2>
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</div>

	<script src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

healthblog/blog/templates/index.html
{% extends 'base.html' %}


{% block subheader %} Top News in Digital Health {% endblock %}



{% block content %}

<div class="container-fluid">
	<u1 class="articles">
		{% for article in articles %}
		<li> 
			<img class="article-image" src="{{ article.publisher.image }}" height=100px width=100px/>
			<a class="article-link" href="/goto/?article_id={{ article.id }}">{{ article.title }}</a>
			<div class="metadata">
				<span class="pub_date">
					<strong>Date published: </strong>{{ article.date_published }}
				</span>
				<br>
				<span class="blurb">
					{{ article.blurb }}
				</span>
				<br>
				<span class="views">
					<strong>Number of views: </strong>{{ article.views }}
				</span>
				{% if article.tag_set.all %}
				<br>	
				<span class="tags">
					<strong>Tags: </strong>
					{% for tag in article.tag_set.all %}
						<a href="{% url 'blog.views.tag' tag.name %}">{{ tag.name }} | </a>
						{% endfor %}
				</span>
				{% endif %}		
		</li>
		<br>
		{% endfor %}
	</ul>
</div>
{% endblock %}

healthblog/blog/templates/tag.html
{% extends 'index.html' %}

{% block subheader %}Articles tagged <i>{{ title }}</i>{% endblock %}

healthblog/blog/templates/tag_list.html
<h3>Topic Tags</h3>
<ul class="nav nav-list">
	{% if topic_tags %}
		{% for tag in topic_tags %}
			<li><a href="{% url 'blog.views.tag' tag.name %}">{{ tag.clean_name }} ({{ tag.article_count }} {% if tag.article_count > 1 %} articles{% elif tag.article_count == 1 %} article{% endif %})</a></li>
		{% endfor %}
	{% else %}
		<li>No categories here.</li>
	{% endif %}
</ul>

<h3>Other Tags</h3>
<ul class="nav nav-list">
	{% if other_tags %}
		{% for tag in other_tags %}
			<li><a href="{% url 'blog.views.tag' tag.name %}">{{ tag.clean_name }} ({{ tag.article_count }} {% if tag.article_count > 1 %} articles{% elif tag.article_count == 1 %} article{% endif %})</a></li>
		{% endfor %}

	{% else %}
		<li>No categories here.</li>
	{% endif %}
</ul>